# SPDX-License-Identifier: GPL-2.0
dtb-y += mt6768.dtb
# dtbo-y += a22/a22_eur_open_w00_r00.dtbo
# dtbo-y += a22/a22_eur_open_w00_r01.dtbo
# dtbo-y += a22/a22_eur_open_w00_r02.dtbo

always            := $(dtb-y) #$(dtbo-y)
clean-files       := *.dtb*
